author: Master-Bw3
book_id: "hex_server:hex_serverbook"
default_branch: 1.20.1
github_repo: hex_server
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexServerModPlugin
hexdoc_plugin_classname: HexServerPlugin
java_lang:
  ext: java
  src: java
java_package: mod/master_bw3/hex_server
mod_display_name: Hex Server
modid: hex_server
multiloader: true
pages_url: https://master-bw3.github.io/hex_server
pattern_regex:
  regex: '(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?'
  per_world_value: registerPerWorld
pattern_registry: registry/HexServerPatterns.java
