# copier-template-tester configuration and default answers

[defaults]
modid = "hexdummy"
author = "artynova"
classname = "HexDummy"
display_name = "Hex Dummy"

[output.".ctt/mojmap"]
mappings_name = "Mojmap"

[output.".ctt/yarn"]
mappings_name = "Yarn"
