# non-minecraft values
org.gradle.jvmargs=-Xmx4096M
jetbrainsAnnotationsVersion=23.0.0

# gradle kotlin jvm plugin breaks without this
kotlin.stdlib.default.dependency=false

# mod info
mavenGroup=mod.master_bw3.hex_server
modId=hex_server
modVersion=0.0.2+1.20.1

# publishing (TODO: fill these in!)
curseforgeId=
modrinthId=
